// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Notes.Model.Model
{
    public partial class notesCntx : DbContext
    {
        public notesCntx()
        {
        }

        public notesCntx(DbContextOptions<notesCntx> options)
            : base(options)
        {
        }

        public virtual DbSet<NotNotes> NotNotes { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer(ConectionDB.GenConectionStr());
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasDefaultSchema("siasani_notes");

            modelBuilder.Entity<NotNotes>(entity =>
            {
                entity.Property(e => e.NotFechaadd).HasDefaultValueSql("(getdate())");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}