// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.Model
{
    [Table("notes")]
    [Index("Title", "Body", Name = "IX_coverage_index_01")]
    [Index("Body", "Title", Name = "IX_coverage_index_02")]
    public partial class Notes
    {
        [Key]
        [Column("id")]
        public long Id { get; set; }
        [Required]
        [Column("title")]
        [StringLength(250)]
        public string Title { get; set; }
        [Column("body")]
        [StringLength(2500)]
        public string Body { get; set; }
        [Column("added", TypeName = "datetime")]
        public DateTime Added { get; set; }
        [Column("modified", TypeName = "datetime")]
        public DateTime? Modified { get; set; }
    }
}