// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Notes.Model.Model
{
    [Table("not_notes")]
    [Index("NotTitle", "NotBody", Name = "IX_Cobertura_01")]
    [Index("NotBody", "NotTitle", Name = "IX_Cobertura_02")]
    public partial class NotNotes
    {
        [Key]
        [Column("not_id")]
        public long NotId { get; set; }
        [Required]
        [Column("not_title")]
        [StringLength(250)]
        public string NotTitle { get; set; }
        [Column("not_body")]
        [StringLength(2500)]
        public string NotBody { get; set; }
        [Column("not_fechaadd", TypeName = "datetime")]
        public DateTime NotFechaadd { get; set; }
        [Column("not_fechamod", TypeName = "datetime")]
        public DateTime? NotFechamod { get; set; }
    }
}