// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Notes.Models;
using Mdl = Data.Model;

namespace Data.Contex
{
    public partial class notesCntx : DbContext
    {
        private readonly IConfiguration _configuration;

        public notesCntx(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public notesCntx(DbContextOptions<notesCntx> options)
            : base(options)
        {
        }

        public virtual DbSet<Model.Notes> Notes { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer((new ConectionDB(_configuration)).GenConectionStr());
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasDefaultSchema("siasani_notes");

            modelBuilder.Entity<Mdl.Notes>(entity =>
            {
                entity.Property(e => e.Added).HasDefaultValueSql("(getdate())");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}